insert into Publicadores (nombre) values ('American black bear'); insert into Publicadores (nombre) values ('Rat, desert kangaroo'); insert into Publicadores (nombre) values ('Pintail, bahama'); insert into Publicadores (nombre) values ('Brown capuchin'); insert into Publicadores (nombre) values ('Anteater, giant'); insert into Publicadores (nombre) values ('Suricate'); insert into Publicadores (nombre) values ('Kangaroo, western grey'); insert into Publicadores (nombre) values ('House crow'); insert into Publicadores (nombre) values ('Langur, hanuman'); insert into Publicadores (nombre) values ('Gazelle, thomson''s'); insert into Publicadores (nombre) values ('Ibis, puna'); insert into Publicadores (nombre) values ('Brown and yellow marshbird'); insert into Publicadores (nombre) values ('River wallaby'); insert into Publicadores (nombre) values ('Kangaroo, brush-tailed rat'); insert into Publicadores (nombre) values ('Green-winged macaw'); insert into Publicadores (nombre) values ('Kangaroo, jungle'); insert into Publicadores (nombre) values ('Phascogale, red-tailed'); insert into Publicadores (nombre) values ('Hawk-eagle, crowned'); insert into Publicadores (nombre) values ('Blue-tongued lizard'); insert into Publicadores (nombre) values ('Cormorant, little'); insert into Publicadores (nombre) values ('Beisa oryx'); insert into Publicadores (nombre) values ('American black bear'); insert into Publicadores (nombre) values ('Squirrel, african bush'); insert into Publicadores (nombre) values ('Goose, cereopsis'); insert into Publicadores (nombre) values ('Killer whale'); insert into Publicadores (nombre) values ('Black and white colobus'); insert into Publicadores (nombre) values ('Topi'); insert into Publicadores (nombre) values ('Toucan, red-billed'); insert into Publicadores (nombre) values ('Stork, openbill'); insert into Publicadores (nombre) values ('Black-crowned night heron'); insert into Publicadores (nombre) values ('Orca'); insert into Publicadores (nombre) values ('Turkey vulture'); insert into Publicadores (nombre) values ('Desert kangaroo rat'); insert into Publicadores (nombre) values ('Sandhill crane'); insert into Publicadores (nombre) values ('Pelican, eastern white'); insert into Publicadores (nombre) values ('Lion, asian'); insert into Publicadores (nombre) values ('Yellow-crowned night heron'); insert into Publicadores (nombre) values ('Brush-tailed phascogale'); insert into Publicadores (nombre) values ('Marshbird, brown and yellow'); insert into Publicadores (nombre) values ('Constrictor, eastern boa'); insert into Publicadores (nombre) values ('Nine-banded armadillo'); insert into Publicadores (nombre) values ('Crab-eating fox'); insert into Publicadores (nombre) values ('Racer, blue'); insert into Publicadores (nombre) values ('Blue crane'); insert into Publicadores (nombre) values ('Deer, savannah'); insert into Publicadores (nombre) values ('Feathertail glider'); insert into Publicadores (nombre) values ('Snake, eastern indigo'); insert into Publicadores (nombre) values ('Small-spotted genet'); insert into Publicadores (nombre) values ('Gray rhea'); insert into Publicadores (nombre) values ('Jackal, asiatic'); insert into Publicadores (nombre) values ('Tailless tenrec'); insert into Publicadores (nombre) values ('Spoonbill, european'); insert into Publicadores (nombre) values ('Eagle, african fish'); insert into Publicadores (nombre) values ('Wallaby, river'); insert into Publicadores (nombre) values ('Crane, stanley'); insert into Publicadores (nombre) values ('Puffin, horned'); insert into Publicadores (nombre) values ('Common pheasant'); insert into Publicadores (nombre) values ('Arctic hare'); insert into Publicadores (nombre) values ('Bear, grizzly'); insert into Publicadores (nombre) values ('Asian false vampire bat'); insert into Publicadores (nombre) values ('European red squirrel'); insert into Publicadores (nombre) values ('Horned rattlesnake'); insert into Publicadores (nombre) values ('Ant (unidentified)'); insert into Publicadores (nombre) values ('European wild cat'); insert into Publicadores (nombre) values ('Cormorant, javanese'); insert into Publicadores (nombre) values ('Possum, western pygmy'); insert into Publicadores (nombre) values ('Bison, american'); insert into Publicadores (nombre) values ('Swan, trumpeter'); insert into Publicadores (nombre) values ('Red-legged pademelon'); insert into Publicadores (nombre) values ('Vulture, lappet-faced'); insert into Publicadores (nombre) values ('Mocking cliffchat'); insert into Publicadores (nombre) values ('Crow, american'); insert into Publicadores (nombre) values ('Waterbuck, common'); insert into Publicadores (nombre) values ('Chameleon (unidentified)'); insert into Publicadores (nombre) values ('Common rhea'); insert into Publicadores (nombre) values ('Heron, green-backed'); insert into Publicadores (nombre) values ('European red squirrel'); insert into Publicadores (nombre) values ('African red-eyed bulbul'); insert into Publicadores (nombre) values ('Columbian rainbow boa'); insert into Publicadores (nombre) values ('Green vine snake'); insert into Publicadores (nombre) values ('Zorro, azara''s'); insert into Publicadores (nombre) values ('Onager'); insert into Publicadores (nombre) values ('Stork, openbill'); insert into Publicadores (nombre) values ('Oriental white-backed vulture'); insert into Publicadores (nombre) values ('Green heron'); insert into Publicadores (nombre) values ('African jacana'); insert into Publicadores (nombre) values ('Phalarope, grey'); insert into Publicadores (nombre) values ('Dog, african wild'); insert into Publicadores (nombre) values ('Turkey, wild'); insert into Publicadores (nombre) values ('Lemur, ring-tailed'); insert into Publicadores (nombre) values ('Kirk''s dik dik'); insert into Publicadores (nombre) values ('Koala'); insert into Publicadores (nombre) values ('Andean goose'); insert into Publicadores (nombre) values ('Springbuck'); insert into Publicadores (nombre) values ('House sparrow'); insert into Publicadores (nombre) values ('Toucan, white-throated'); insert into Publicadores (nombre) values ('Jackal, black-backed'); insert into Publicadores (nombre) values ('African elephant'); insert into Publicadores (nombre) values ('Mule deer'); insert into Publicadores (nombre) values ('Gazelle, grant''s');

insert into Desarrolladores (nombre) values ('Tadorna tadorna');
insert into Desarrolladores (nombre) values ('Sciurus vulgaris');
insert into Desarrolladores (nombre) values ('Terathopius ecaudatus');
insert into Desarrolladores (nombre) values ('Elephas maximus bengalensis');
insert into Desarrolladores (nombre) values ('Ploceus rubiginosus');
insert into Desarrolladores (nombre) values ('Ciconia episcopus');
insert into Desarrolladores (nombre) values ('Terrapene carolina');
insert into Desarrolladores (nombre) values ('Mirounga angustirostris');
insert into Desarrolladores (nombre) values ('Passer domesticus');
insert into Desarrolladores (nombre) values ('Zosterops pallidus');
insert into Desarrolladores (nombre) values ('Charadrius tricollaris');
insert into Desarrolladores (nombre) values ('Smithopsis crassicaudata');
insert into Desarrolladores (nombre) values ('Crotalus cerastes');
insert into Desarrolladores (nombre) values ('Irania gutteralis');
insert into Desarrolladores (nombre) values ('Psophia viridis');
insert into Desarrolladores (nombre) values ('Axis axis');
insert into Desarrolladores (nombre) values ('Alopochen aegyptiacus');
insert into Desarrolladores (nombre) values ('Sula nebouxii');
insert into Desarrolladores (nombre) values ('Alces alces');
insert into Desarrolladores (nombre) values ('Felis yagouaroundi');
insert into Desarrolladores (nombre) values ('Semnopithecus entellus');
insert into Desarrolladores (nombre) values ('Canis mesomelas');
insert into Desarrolladores (nombre) values ('Actophilornis africanus');
insert into Desarrolladores (nombre) values ('Cebus apella');
insert into Desarrolladores (nombre) values ('Semnopithecus entellus');
insert into Desarrolladores (nombre) values ('Notechis semmiannulatus');
insert into Desarrolladores (nombre) values ('Ornithorhynchus anatinus');
insert into Desarrolladores (nombre) values ('Alopex lagopus');
insert into Desarrolladores (nombre) values ('Phalaropus lobatus');
insert into Desarrolladores (nombre) values ('Damaliscus dorcas');
insert into Desarrolladores (nombre) values ('Panthera leo');
insert into Desarrolladores (nombre) values ('Agkistrodon piscivorus');
insert into Desarrolladores (nombre) values ('unavailable');
insert into Desarrolladores (nombre) values ('Dusicyon thous');
insert into Desarrolladores (nombre) values ('Naja nivea');
insert into Desarrolladores (nombre) values ('Rhea americana');
insert into Desarrolladores (nombre) values ('Dasypus septemcincus');
insert into Desarrolladores (nombre) values ('Uraeginthus granatina');
insert into Desarrolladores (nombre) values ('Leprocaulinus vipera');
insert into Desarrolladores (nombre) values ('Tockus erythrorhyncus');
insert into Desarrolladores (nombre) values ('Panthera leo');
insert into Desarrolladores (nombre) values ('Passer domesticus');
insert into Desarrolladores (nombre) values ('Bubulcus ibis');
insert into Desarrolladores (nombre) values ('Phalaropus lobatus');
insert into Desarrolladores (nombre) values ('Ephippiorhynchus mycteria');
insert into Desarrolladores (nombre) values ('Bugeranus caruncalatus');
insert into Desarrolladores (nombre) values ('Cordylus giganteus');
insert into Desarrolladores (nombre) values ('Stercorarius longicausus');
insert into Desarrolladores (nombre) values ('Canis dingo');
insert into Desarrolladores (nombre) values ('Stercorarius longicausus');
insert into Desarrolladores (nombre) values ('Castor canadensis');
insert into Desarrolladores (nombre) values ('Ephipplorhynchus senegalensis');
insert into Desarrolladores (nombre) values ('Gymnorhina tibicen');
insert into Desarrolladores (nombre) values ('Phalacrocorax carbo');
insert into Desarrolladores (nombre) values ('Dasyurus maculatus');
insert into Desarrolladores (nombre) values ('Meleagris gallopavo');
insert into Desarrolladores (nombre) values ('Choriotis kori');
insert into Desarrolladores (nombre) values ('Elephas maximus bengalensis');
insert into Desarrolladores (nombre) values ('Eudyptula minor');
insert into Desarrolladores (nombre) values ('Castor canadensis');
insert into Desarrolladores (nombre) values ('Balearica pavonina');
insert into Desarrolladores (nombre) values ('Trichechus inunguis');
insert into Desarrolladores (nombre) values ('Anas platyrhynchos');
insert into Desarrolladores (nombre) values ('Tachyglossus aculeatus');
insert into Desarrolladores (nombre) values ('Pteronura brasiliensis');
insert into Desarrolladores (nombre) values ('Ara macao');
insert into Desarrolladores (nombre) values ('Marmota caligata');
insert into Desarrolladores (nombre) values ('Nycticorax nycticorax');
insert into Desarrolladores (nombre) values ('Theropithecus gelada');
insert into Desarrolladores (nombre) values ('Francolinus coqui');
insert into Desarrolladores (nombre) values ('Colobus guerza');
insert into Desarrolladores (nombre) values ('Melanerpes erythrocephalus');
insert into Desarrolladores (nombre) values ('Cervus elaphus');
insert into Desarrolladores (nombre) values ('Phasianus colchicus');
insert into Desarrolladores (nombre) values ('Halcyon smyrnesis');
insert into Desarrolladores (nombre) values ('Manouria emys');
insert into Desarrolladores (nombre) values ('Callipepla gambelii');
insert into Desarrolladores (nombre) values ('Genetta genetta');
insert into Desarrolladores (nombre) values ('Choloepus hoffmani');
insert into Desarrolladores (nombre) values ('Vulpes vulpes');
insert into Desarrolladores (nombre) values ('Alopochen aegyptiacus');
insert into Desarrolladores (nombre) values ('Macropus eugenii');
insert into Desarrolladores (nombre) values ('Meles meles');
insert into Desarrolladores (nombre) values ('Fulica cristata');
insert into Desarrolladores (nombre) values ('Rangifer tarandus');
insert into Desarrolladores (nombre) values ('Cordylus giganteus');
insert into Desarrolladores (nombre) values ('Canis lupus baileyi');
insert into Desarrolladores (nombre) values ('Lycaon pictus');
insert into Desarrolladores (nombre) values ('Ammospermophilus nelsoni');
insert into Desarrolladores (nombre) values ('Limosa haemastica');
insert into Desarrolladores (nombre) values ('Casmerodius albus');
insert into Desarrolladores (nombre) values ('unavailable');
insert into Desarrolladores (nombre) values ('Columba livia');
insert into Desarrolladores (nombre) values ('Perameles nasuta');
insert into Desarrolladores (nombre) values ('Actophilornis africanus');
insert into Desarrolladores (nombre) values ('Ploceus intermedius');
insert into Desarrolladores (nombre) values ('Camelus dromedarius');
insert into Desarrolladores (nombre) values ('Manouria emys');
insert into Desarrolladores (nombre) values ('Rangifer tarandus');
insert into Desarrolladores (nombre) values ('Ara chloroptera');

insert into Clientes (email, contraseña, nombre, cartera) values ('rwylam0@zdnet.com', 'DDLAS', 'Rici', 9);
insert into Clientes (email, contraseña, nombre, cartera) values ('ddowthwaite1@storify.com', 'DDLAS', 'Daryle', 341);
insert into Clientes (email, contraseña, nombre, cartera) values ('jgipps2@ning.com', 'DDLAS', 'Jeni', 689);
insert into Clientes (email, contraseña, nombre, cartera) values ('gduigenan3@jalbum.net', 'DDLAS', 'Geoffrey', 767);
insert into Clientes (email, contraseña, nombre, cartera) values ('dbosson4@artisteer.com', 'DDLAS', 'Desmund', 347);
insert into Clientes (email, contraseña, nombre, cartera) values ('bminshaw5@wiley.com', 'DDLAS', 'Barrett', 351);
insert into Clientes (email, contraseña, nombre, cartera) values ('phawkins6@cbsnews.com', 'DDLAS', 'Phoebe', 291);
insert into Clientes (email, contraseña, nombre, cartera) values ('jstuddard7@mapy.cz', 'DDLAS', 'Jayme', 534);
insert into Clientes (email, contraseña, nombre, cartera) values ('zbartusek8@usnews.com', 'DDLAS', 'Zonda', 706);
insert into Clientes (email, contraseña, nombre, cartera) values ('ksilwood9@timesonline.co.uk', 'DDLAS', 'Klaus', 163);
insert into Clientes (email, contraseña, nombre, cartera) values ('grustona@ucla.edu', 'DDLAS', 'Gram', 449);
insert into Clientes (email, contraseña, nombre, cartera) values ('erichb@usda.gov', 'DDLAS', 'Ewell', 173);
insert into Clientes (email, contraseña, nombre, cartera) values ('ckleinpeltzc@netlog.com', 'DDLAS', 'Camella', 835);
insert into Clientes (email, contraseña, nombre, cartera) values ('eventhamd@behance.net', 'DDLAS', 'Ellsworth', 519);
insert into Clientes (email, contraseña, nombre, cartera) values ('ccherrye@seesaa.net', 'DDLAS', 'Cherise', 997);
insert into Clientes (email, contraseña, nombre, cartera) values ('korrobinf@toplist.cz', 'DDLAS', 'Kurtis', 459);
insert into Clientes (email, contraseña, nombre, cartera) values ('rtrumbleg@fema.gov', 'DDLAS', 'Rochella', 455);
insert into Clientes (email, contraseña, nombre, cartera) values ('jfeckeyh@sun.com', 'DDLAS', 'Jonas', 250);
insert into Clientes (email, contraseña, nombre, cartera) values ('gpardoei@usnews.com', 'DDLAS', 'Garreth', 601);
insert into Clientes (email, contraseña, nombre, cartera) values ('acobbyj@wired.com', 'DDLAS', 'Arnaldo', 759);
insert into Clientes (email, contraseña, nombre, cartera) values ('nsommerk@mapy.cz', 'DDLAS', 'Natalina', 143);
insert into Clientes (email, contraseña, nombre, cartera) values ('kroisl@opera.com', 'DDLAS', 'Karrie', 542);
insert into Clientes (email, contraseña, nombre, cartera) values ('scronm@etsy.com', 'DDLAS', 'Sayre', 250);
insert into Clientes (email, contraseña, nombre, cartera) values ('mpaddelln@deliciousdays.com', 'DDLAS', 'Mel', 658);
insert into Clientes (email, contraseña, nombre, cartera) values ('kscothrono@ucoz.com', 'DDLAS', 'Kellina', 932);
insert into Clientes (email, contraseña, nombre, cartera) values ('cmcaulayp@linkedin.com', 'DDLAS', 'Casper', 706);
insert into Clientes (email, contraseña, nombre, cartera) values ('hkidsleyq@mac.com', 'DDLAS', 'Hillier', 406);
insert into Clientes (email, contraseña, nombre, cartera) values ('cwarrackr@1und1.de', 'DDLAS', 'Cam', 733);
insert into Clientes (email, contraseña, nombre, cartera) values ('jcreaseys@si.edu', 'DDLAS', 'Juanita', 186);
insert into Clientes (email, contraseña, nombre, cartera) values ('kshillabeert@usatoday.com', 'DDLAS', 'Kahlil', 796);
insert into Clientes (email, contraseña, nombre, cartera) values ('jhumbeyu@china.com.cn', 'DDLAS', 'Jeanie', 635);
insert into Clientes (email, contraseña, nombre, cartera) values ('tcruttendenv@miitbeian.gov.cn', 'DDLAS', 'Teirtza', 94);
insert into Clientes (email, contraseña, nombre, cartera) values ('kedlingtonw@wikipedia.org', 'DDLAS', 'Kore', 147);
insert into Clientes (email, contraseña, nombre, cartera) values ('meastgatex@blogger.com', 'DDLAS', 'Malva', 966);
insert into Clientes (email, contraseña, nombre, cartera) values ('tfrancklyny@hao123.com', 'DDLAS', 'Tersina', 947);
insert into Clientes (email, contraseña, nombre, cartera) values ('amurrumz@google.de', 'DDLAS', 'Allegra', 931);
insert into Clientes (email, contraseña, nombre, cartera) values ('laldington10@php.net', 'DDLAS', 'Lynette', 623);
insert into Clientes (email, contraseña, nombre, cartera) values ('rswateridge11@abc.net.au', 'DDLAS', 'Rainer', 384);
insert into Clientes (email, contraseña, nombre, cartera) values ('nbellanger12@php.net', 'DDLAS', 'Nancee', 624);
insert into Clientes (email, contraseña, nombre, cartera) values ('rbenedettini13@msu.edu', 'DDLAS', 'Rudd', 58);
insert into Clientes (email, contraseña, nombre, cartera) values ('bethelston14@163.com', 'DDLAS', 'Bibbie', 891);
insert into Clientes (email, contraseña, nombre, cartera) values ('ddaoust15@admin.ch', 'DDLAS', 'Darby', 724);
insert into Clientes (email, contraseña, nombre, cartera) values ('pitzcovichch16@alibaba.com', 'DDLAS', 'Perri', 849);
insert into Clientes (email, contraseña, nombre, cartera) values ('tcoweuppe17@economist.com', 'DDLAS', 'Tamma', 18);
insert into Clientes (email, contraseña, nombre, cartera) values ('bstuart18@time.com', 'DDLAS', 'Britney', 169);
insert into Clientes (email, contraseña, nombre, cartera) values ('bsherbrook19@zimbio.com', 'DDLAS', 'Barny', 757);
insert into Clientes (email, contraseña, nombre, cartera) values ('cconigsby1a@microsoft.com', 'DDLAS', 'Corrine', 2);
insert into Clientes (email, contraseña, nombre, cartera) values ('agrelka1b@dell.com', 'DDLAS', 'Aryn', 886);
insert into Clientes (email, contraseña, nombre, cartera) values ('bchaucer1c@photobucket.com', 'DDLAS', 'Bobbye', 663);
insert into Clientes (email, contraseña, nombre, cartera) values ('calans1d@e-recht24.de', 'DDLAS', 'Corbet', 106);
insert into Clientes (email, contraseña, nombre, cartera) values ('babrahmovici1e@jiathis.com', 'DDLAS', 'Baldwin', 374);
insert into Clientes (email, contraseña, nombre, cartera) values ('pglisane1f@mashable.com', 'DDLAS', 'Patin', 42);
insert into Clientes (email, contraseña, nombre, cartera) values ('tbursnell1g@blogtalkradio.com', 'DDLAS', 'Tristan', 327);
insert into Clientes (email, contraseña, nombre, cartera) values ('zbierton1h@businesswire.com', 'DDLAS', 'Zedekiah', 909);
insert into Clientes (email, contraseña, nombre, cartera) values ('gkunrad1i@usa.gov', 'DDLAS', 'Giselle', 816);
insert into Clientes (email, contraseña, nombre, cartera) values ('tbillie1j@de.vu', 'DDLAS', 'Tabbie', 155);
insert into Clientes (email, contraseña, nombre, cartera) values ('gmchan1k@smugmug.com', 'DDLAS', 'Gaspard', 29);
insert into Clientes (email, contraseña, nombre, cartera) values ('preast1l@digg.com', 'DDLAS', 'Patsy', 367);
insert into Clientes (email, contraseña, nombre, cartera) values ('lspurgeon1m@hud.gov', 'DDLAS', 'Lilian', 881);
insert into Clientes (email, contraseña, nombre, cartera) values ('abenion1n@cdc.gov', 'DDLAS', 'Annalee', 608);
insert into Clientes (email, contraseña, nombre, cartera) values ('lbagge1o@hc360.com', 'DDLAS', 'Lu', 50);
insert into Clientes (email, contraseña, nombre, cartera) values ('lbutchers1p@goo.ne.jp', 'DDLAS', 'Lee', 945);
insert into Clientes (email, contraseña, nombre, cartera) values ('eocrigan1q@statcounter.com', 'DDLAS', 'Ethelyn', 726);
insert into Clientes (email, contraseña, nombre, cartera) values ('igather1r@zdnet.com', 'DDLAS', 'Isadora', 637);
insert into Clientes (email, contraseña, nombre, cartera) values ('sgoundsy1s@ed.gov', 'DDLAS', 'Sisely', 762);
insert into Clientes (email, contraseña, nombre, cartera) values ('kskittreal1t@msn.com', 'DDLAS', 'Karlens', 651);
insert into Clientes (email, contraseña, nombre, cartera) values ('ahowton1u@yahoo.co.jp', 'DDLAS', 'Annelise', 107);
insert into Clientes (email, contraseña, nombre, cartera) values ('odowglass1v@nifty.com', 'DDLAS', 'Otho', 360);
insert into Clientes (email, contraseña, nombre, cartera) values ('bpassmore1w@google.de', 'DDLAS', 'Bayard', 639);
insert into Clientes (email, contraseña, nombre, cartera) values ('fhiggen1x@example.com', 'DDLAS', 'Farlee', 819);
insert into Clientes (email, contraseña, nombre, cartera) values ('adarrell1y@craigslist.org', 'DDLAS', 'Amii', 674);
insert into Clientes (email, contraseña, nombre, cartera) values ('mbannell1z@wp.com', 'DDLAS', 'Mildrid', 628);
insert into Clientes (email, contraseña, nombre, cartera) values ('lbanting20@is.gd', 'DDLAS', 'Lamar', 831);
insert into Clientes (email, contraseña, nombre, cartera) values ('bandrioli21@census.gov', 'DDLAS', 'Buiron', 425);
insert into Clientes (email, contraseña, nombre, cartera) values ('rtamsett22@fema.gov', 'DDLAS', 'Robinette', 945);
insert into Clientes (email, contraseña, nombre, cartera) values ('vcostar23@ibm.com', 'DDLAS', 'Vernon', 640);
insert into Clientes (email, contraseña, nombre, cartera) values ('ebrooksbank24@bloomberg.com', 'DDLAS', 'Eleanore', 367);
insert into Clientes (email, contraseña, nombre, cartera) values ('esherer25@vkontakte.ru', 'DDLAS', 'Ellis', 206);
insert into Clientes (email, contraseña, nombre, cartera) values ('pkall26@aol.com', 'DDLAS', 'Philippa', 644);
insert into Clientes (email, contraseña, nombre, cartera) values ('ludell27@diigo.com', 'DDLAS', 'Lacy', 63);
insert into Clientes (email, contraseña, nombre, cartera) values ('tbygreaves28@army.mil', 'DDLAS', 'Timmy', 51);
insert into Clientes (email, contraseña, nombre, cartera) values ('lomonahan29@instagram.com', 'DDLAS', 'Lucienne', 925);
insert into Clientes (email, contraseña, nombre, cartera) values ('lciardo2a@senate.gov', 'DDLAS', 'Lowrance', 664);
insert into Clientes (email, contraseña, nombre, cartera) values ('kgouldstone2b@prweb.com', 'DDLAS', 'Kinnie', 583);
insert into Clientes (email, contraseña, nombre, cartera) values ('svolker2c@posterous.com', 'DDLAS', 'Sibyl', 871);
insert into Clientes (email, contraseña, nombre, cartera) values ('dwaterhowse2d@e-recht24.de', 'DDLAS', 'Durante', 372);
insert into Clientes (email, contraseña, nombre, cartera) values ('ldunstan2e@accuweather.com', 'DDLAS', 'Larine', 859);
insert into Clientes (email, contraseña, nombre, cartera) values ('dslowcock2f@so-net.ne.jp', 'DDLAS', 'Ddene', 724);
insert into Clientes (email, contraseña, nombre, cartera) values ('eelton2g@theglobeandmail.com', 'DDLAS', 'Ethelda', 467);
insert into Clientes (email, contraseña, nombre, cartera) values ('mwardingley2h@telegraph.co.uk', 'DDLAS', 'Malena', 31);
insert into Clientes (email, contraseña, nombre, cartera) values ('bskerm2i@thetimes.co.uk', 'DDLAS', 'Brier', 205);
insert into Clientes (email, contraseña, nombre, cartera) values ('rtytcomb2j@amazon.de', 'DDLAS', 'Roseanne', 866);
insert into Clientes (email, contraseña, nombre, cartera) values ('cshoosmith2k@eepurl.com', 'DDLAS', 'Catie', 526);
insert into Clientes (email, contraseña, nombre, cartera) values ('krubinsky2l@livejournal.com', 'DDLAS', 'Kirsten', 980);
insert into Clientes (email, contraseña, nombre, cartera) values ('oedlestone2m@bloomberg.com', 'DDLAS', 'Odell', 743);
insert into Clientes (email, contraseña, nombre, cartera) values ('rbudnik2n@privacy.gov.au', 'DDLAS', 'Rani', 6);
insert into Clientes (email, contraseña, nombre, cartera) values ('jbambury2o@archive.org', 'DDLAS', 'Jordon', 561);
insert into Clientes (email, contraseña, nombre, cartera) values ('oclapton2p@parallels.com', 'DDLAS', 'Odille', 108);
insert into Clientes (email, contraseña, nombre, cartera) values ('bnewing2q@icio.us', 'DDLAS', 'Birgit', 464);
insert into Clientes (email, contraseña, nombre, cartera) values ('jcathie2r@ustream.tv', 'DDLAS', 'Jenifer', 829);
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Fun', 301, '2020-12-10', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Predictions of Fire (Prerokbe Ognja)', 336, '2020-10-07', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Beachhead', 371, '2019-03-03', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('All Things to All Men', 80, '2021-12-26', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Field, The', 106, '2020-05-05', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('13/13/13', 111, '2019-10-23', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Solomon Kane', 93, '2021-10-04', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Katyn', 24, '2019-08-30', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('What''s Cooking?', 409, '2022-03-23', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Suck', 66, '2021-01-27', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Couples Retreat', 440, '2022-01-06', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Santo vs. las lobas', 251, '2021-07-16', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Happy', 55, '2021-12-31', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Hamlet', 186, '2020-12-08', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Something Borrowed', 388, '2021-02-04', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Sword of Gideon', 424, '2019-11-09', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Slammin'' Salmon, The', 402, '2020-08-15', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Hamlet', 59, '2021-09-12', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Particle Fever', 420, '2021-08-12', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Contagion / Bio Slime', 429, '2020-02-20', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Scusa ma ti chiamo amore', 19, '2020-01-11', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Next Karate Kid, The', 419, '2021-11-12', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Raven, The', 85, '2021-08-20', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Celine: Through the Eyes of the World', 67, '2019-09-23', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Masque of the Red Death, The', 400, '2021-03-08', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Fox, The', 217, '2022-02-09', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Nasty Girl, The (schreckliche MÃ¤dchen, Das)', 428, '2020-04-08', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Lost Boys of Sudan', 10, '2021-03-25', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Marvellous', 473, '2020-11-06', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Sommersby', 358, '2022-05-12', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Speedway', 48, '2021-02-19', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Jumping the Broom', 320, '2019-11-10', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Faithless (TrolÃ¶sa)', 399, '2019-12-25', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Devil Doll', 296, '2021-05-13', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Lost Patrol, The', 65, '2020-07-05', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Robot Stories', 179, '2019-10-08', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Song to Remember, A', 10, '2019-07-02', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('My Girlfriend Is an Agent (Chilgeup gongmuwon)', 433, '2019-05-17', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Casablanca Express', 269, '2020-09-17', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Run, Man, Run! (Corri uomo corri)', 359, '2020-09-18', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Winged Migration (Peuple migrateur, Le)', 476, '2019-05-08', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Anger Management', 482, '2021-02-27', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Moon of the Wolf', 96, '2021-10-10', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('House on Haunted Hill', 350, '2021-07-17', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Summer Rental', 212, '2019-05-02', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Enemy Mine', 163, '2021-07-23', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Cleanskin', 321, '2020-06-14', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Oxy-Morons', 299, '2021-07-18', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Bag It', 420, '2022-03-14', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Breakout', 371, '2019-04-17', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Central Park Five, The', 246, '2019-09-18', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('All This, and Heaven Too', 413, '2020-03-30', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Good Morning, Babylon', 49, '2021-06-26', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('C.O.G.', 474, '2022-02-15', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Jackass: The Movie', 368, '2021-09-28', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Thing from Another World, The', 412, '2022-03-30', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Redacted', 378, '2021-07-03', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Waiting Room, The', 202, '2022-01-05', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Autumn in New York', 2, '2019-11-30', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Thrill of It All, The', 91, '2020-01-02', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Barbie: A Perfect Christmas', 312, '2020-10-31', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Jules and Jim (Jules et Jim)', 19, '2020-06-13', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Man on Wire', 219, '2021-07-29', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Clownhouse', 25, '2020-03-21', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Sharknado 2: The Second One', 279, '2020-02-03', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Last American Hero, The', 271, '2022-03-09', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Io Island (Iodo)', 118, '2022-01-12', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Exit to Hell', 366, '2021-10-07', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Futureworld', 56, '2021-03-24', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Before the Rains', 232, '2021-05-28', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Dot and the Whale', 28, '2021-01-10', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Beach Red', 152, '2019-11-01', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Conviction', 200, '2021-11-18', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Dam Busters, The', 69, '2020-10-04', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Gumball Rally, The', 101, '2020-12-05', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Flubber', 72, '2019-07-01', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Captive, The (La captive)', 99, '2020-01-24', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Horse Boy, The', 329, '2021-12-15', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Bunny and the Bull', 210, '2020-04-12', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Hava Nagila: The Movie', 9, '2019-03-07', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Nocturno 29', 354, '2021-09-21', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Mr. Wonderful', 356, '2019-07-16', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Miss Potter', 473, '2020-04-23', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Mercy Streets', 128, '2022-04-07', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Bloody Sunday', 488, '2021-07-01', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('De la servitude moderne', 492, '2019-05-21', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Horrible Bosses', 308, '2019-02-21', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Freedomfighters (Libertarias)', 2, '2020-10-07', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Amazing Johnathan: Wrong on Every Level', 89, '2019-09-18', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Box, The', 127, '2021-03-19', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Funeral in Berlin', 34, '2020-05-09', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Battle Hymn', 134, '2019-08-30', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('Smiles of a Summer Night (Sommarnattens leende)', 76, '2021-04-15', 'Insert desc');
insert into Juegos (nombre, precio, fecha_salida, descripcion) values ('The Magnificent Trio', 493, '2020-03-25', 'Insert desc');
insert into Publicadorjuegos (id, id_publicador) values (1, 1);
insert into Publicadorjuegos (id, id_publicador) values (2, 2);
insert into Publicadorjuegos (id, id_publicador) values (3, 3);
insert into Publicadorjuegos (id, id_publicador) values (4, 4);
insert into Publicadorjuegos (id, id_publicador) values (5, 5);


insert into Publicadorjuegos (id, id_publicador) values (6, 6);
insert into Publicadorjuegos (id, id_publicador) values (7, 7);
insert into Publicadorjuegos (id, id_publicador) values (8, 8);
insert into Publicadorjuegos (id, id_publicador) values (9, 9);
insert into Publicadorjuegos (id, id_publicador) values (10, 10);
insert into Publicadorjuegos (id, id_publicador) values (11, 11);
insert into Publicadorjuegos (id, id_publicador) values (12, 12);
insert into Publicadorjuegos (id, id_publicador) values (13, 13);
insert into Publicadorjuegos (id, id_publicador) values (14, 14);
insert into Publicadorjuegos (id, id_publicador) values (15, 15);
insert into Publicadorjuegos (id, id_publicador) values (16, 16);
insert into Publicadorjuegos (id, id_publicador) values (17, 17);
insert into Publicadorjuegos (id, id_publicador) values (18, 18);
insert into Publicadorjuegos (id, id_publicador) values (19, 19);
insert into Publicadorjuegos (id, id_publicador) values (20, 20);
insert into Publicadorjuegos (id, id_publicador) values (21, 21);
insert into Publicadorjuegos (id, id_publicador) values (22, 22);
insert into Publicadorjuegos (id, id_publicador) values (23, 23);
insert into Publicadorjuegos (id, id_publicador) values (24, 24);
insert into Publicadorjuegos (id, id_publicador) values (25, 25);
insert into Publicadorjuegos (id, id_publicador) values (26, 26);
insert into Publicadorjuegos (id, id_publicador) values (27, 27);
insert into Publicadorjuegos (id, id_publicador) values (28, 28);
insert into Publicadorjuegos (id, id_publicador) values (29, 29);
insert into Publicadorjuegos (id, id_publicador) values (30, 30);
insert into Publicadorjuegos (id, id_publicador) values (31, 31);
insert into Publicadorjuegos (id, id_publicador) values (32, 32);
insert into Publicadorjuegos (id, id_publicador) values (33, 33);
insert into Publicadorjuegos (id, id_publicador) values (34, 34);
insert into Publicadorjuegos (id, id_publicador) values (35, 35);
insert into Publicadorjuegos (id, id_publicador) values (36, 36);
insert into Publicadorjuegos (id, id_publicador) values (37, 37);
insert into Publicadorjuegos (id, id_publicador) values (38, 38);
insert into Publicadorjuegos (id, id_publicador) values (39, 39);
insert into Publicadorjuegos (id, id_publicador) values (40, 40);
insert into Publicadorjuegos (id, id_publicador) values (41, 41);
insert into Publicadorjuegos (id, id_publicador) values (42, 42);
insert into Publicadorjuegos (id, id_publicador) values (43, 43);
insert into Publicadorjuegos (id, id_publicador) values (44, 44);
insert into Publicadorjuegos (id, id_publicador) values (45, 45);
insert into Publicadorjuegos (id, id_publicador) values (46, 46);
insert into Publicadorjuegos (id, id_publicador) values (47, 47);
insert into Publicadorjuegos (id, id_publicador) values (48, 48);
insert into Publicadorjuegos (id, id_publicador) values (49, 49);
insert into Publicadorjuegos (id, id_publicador) values (50, 50);
insert into Publicadorjuegos (id, id_publicador) values (51, 51);
insert into Publicadorjuegos (id, id_publicador) values (52, 52);
insert into Publicadorjuegos (id, id_publicador) values (53, 53);
insert into Publicadorjuegos (id, id_publicador) values (54, 54);
insert into Publicadorjuegos (id, id_publicador) values (55, 55);
insert into Publicadorjuegos (id, id_publicador) values (56, 56);
insert into Publicadorjuegos (id, id_publicador) values (57, 57);
insert into Publicadorjuegos (id, id_publicador) values (58, 58);
insert into Publicadorjuegos (id, id_publicador) values (59, 59);
insert into Publicadorjuegos (id, id_publicador) values (60, 60);
insert into Publicadorjuegos (id, id_publicador) values (61, 61);
insert into Publicadorjuegos (id, id_publicador) values (62, 62);
insert into Publicadorjuegos (id, id_publicador) values (63, 63);
insert into Publicadorjuegos (id, id_publicador) values (64, 64);
insert into Publicadorjuegos (id, id_publicador) values (65, 65);
insert into Publicadorjuegos (id, id_publicador) values (66, 66);
insert into Publicadorjuegos (id, id_publicador) values (67, 67);
insert into Publicadorjuegos (id, id_publicador) values (68, 68);
insert into Publicadorjuegos (id, id_publicador) values (69, 69);
insert into Publicadorjuegos (id, id_publicador) values (70, 70);
insert into Publicadorjuegos (id, id_publicador) values (71, 71);
insert into Publicadorjuegos (id, id_publicador) values (72, 72);
insert into Publicadorjuegos (id, id_publicador) values (73, 73);
insert into Publicadorjuegos (id, id_publicador) values (74, 74);
insert into Publicadorjuegos (id, id_publicador) values (75, 75);
insert into Publicadorjuegos (id, id_publicador) values (76, 76);
insert into Publicadorjuegos (id, id_publicador) values (77, 77);
insert into Publicadorjuegos (id, id_publicador) values (78, 78);
insert into Publicadorjuegos (id, id_publicador) values (79, 79);
insert into Publicadorjuegos (id, id_publicador) values (80, 80);
insert into Publicadorjuegos (id, id_publicador) values (81, 81);
insert into Publicadorjuegos (id, id_publicador) values (82, 82);
insert into Publicadorjuegos (id, id_publicador) values (83, 83);
insert into Publicadorjuegos (id, id_publicador) values (84, 84);
insert into Publicadorjuegos (id, id_publicador) values (85, 85);
insert into Publicadorjuegos (id, id_publicador) values (86, 86);
insert into Publicadorjuegos (id, id_publicador) values (87, 87);
insert into Publicadorjuegos (id, id_publicador) values (88, 88);
insert into Publicadorjuegos (id, id_publicador) values (89, 89);
insert into Publicadorjuegos (id, id_publicador) values (90, 90);
insert into Publicadorjuegos (id, id_publicador) values (91, 91);
insert into Publicadorjuegos (id, id_publicador) values (92, 92);
insert into Publicadorjuegos (id, id_publicador) values (93, 93);
insert into Publicadorjuegos (id, id_publicador) values (94, 94);

insert into Desarrolladorjuegos (id, id_des) values (1, 1);
insert into Desarrolladorjuegos (id, id_des) values (2, 2);
insert into Desarrolladorjuegos (id, id_des) values (3, 3);
insert into Desarrolladorjuegos (id, id_des) values (4, 4);
insert into Desarrolladorjuegos (id, id_des) values (5, 5);
insert into Desarrolladorjuegos (id, id_des) values (6, 6);
insert into Desarrolladorjuegos (id, id_des) values (7, 7);
insert into Desarrolladorjuegos (id, id_des) values (8, 8);
insert into Desarrolladorjuegos (id, id_des) values (9, 9);
insert into Desarrolladorjuegos (id, id_des) values (10, 10);
insert into Desarrolladorjuegos (id, id_des) values (11, 11);
insert into Desarrolladorjuegos (id, id_des) values (12, 12);
insert into Desarrolladorjuegos (id, id_des) values (13, 13);
insert into Desarrolladorjuegos (id, id_des) values (14, 14);
insert into Desarrolladorjuegos (id, id_des) values (15, 15);
insert into Desarrolladorjuegos (id, id_des) values (16, 16);
insert into Desarrolladorjuegos (id, id_des) values (17, 17);
insert into Desarrolladorjuegos (id, id_des) values (18, 18);
insert into Desarrolladorjuegos (id, id_des) values (19, 19);
insert into Desarrolladorjuegos (id, id_des) values (20, 20);
insert into Desarrolladorjuegos (id, id_des) values (21, 21);
insert into Desarrolladorjuegos (id, id_des) values (22, 22);
insert into Desarrolladorjuegos (id, id_des) values (23, 23);
insert into Desarrolladorjuegos (id, id_des) values (24, 24);
insert into Desarrolladorjuegos (id, id_des) values (25, 25);
insert into Desarrolladorjuegos (id, id_des) values (26, 26);
insert into Desarrolladorjuegos (id, id_des) values (27, 27);
insert into Desarrolladorjuegos (id, id_des) values (28, 28);
insert into Desarrolladorjuegos (id, id_des) values (29, 29);
insert into Desarrolladorjuegos (id, id_des) values (30, 30);
insert into Desarrolladorjuegos (id, id_des) values (31, 31);
insert into Desarrolladorjuegos (id, id_des) values (32, 32);
insert into Desarrolladorjuegos (id, id_des) values (33, 33);
insert into Desarrolladorjuegos (id, id_des) values (34, 34);
insert into Desarrolladorjuegos (id, id_des) values (35, 35);
insert into Desarrolladorjuegos (id, id_des) values (36, 36);
insert into Desarrolladorjuegos (id, id_des) values (37, 37);
insert into Desarrolladorjuegos (id, id_des) values (38, 38);
insert into Desarrolladorjuegos (id, id_des) values (39, 39);
insert into Desarrolladorjuegos (id, id_des) values (40, 40);
insert into Desarrolladorjuegos (id, id_des) values (41, 41);
insert into Desarrolladorjuegos (id, id_des) values (42, 42);
insert into Desarrolladorjuegos (id, id_des) values (43, 43);
insert into Desarrolladorjuegos (id, id_des) values (44, 44);
insert into Desarrolladorjuegos (id, id_des) values (45, 45);
insert into Desarrolladorjuegos (id, id_des) values (46, 46);
insert into Desarrolladorjuegos (id, id_des) values (47, 47);
insert into Desarrolladorjuegos (id, id_des) values (48, 48);
insert into Desarrolladorjuegos (id, id_des) values (49, 49);
insert into Desarrolladorjuegos (id, id_des) values (50, 50);
insert into Desarrolladorjuegos (id, id_des) values (51, 51);
insert into Desarrolladorjuegos (id, id_des) values (52, 52);
insert into Desarrolladorjuegos (id, id_des) values (53, 53);
insert into Desarrolladorjuegos (id, id_des) values (54, 54);
insert into Desarrolladorjuegos (id, id_des) values (55, 55);
insert into Desarrolladorjuegos (id, id_des) values (56, 56);
insert into Desarrolladorjuegos (id, id_des) values (57, 57);
insert into Desarrolladorjuegos (id, id_des) values (58, 58);
insert into Desarrolladorjuegos (id, id_des) values (59, 59);
insert into Desarrolladorjuegos (id, id_des) values (60, 60);
insert into Desarrolladorjuegos (id, id_des) values (61, 61);
insert into Desarrolladorjuegos (id, id_des) values (62, 62);
insert into Desarrolladorjuegos (id, id_des) values (63, 63);
insert into Desarrolladorjuegos (id, id_des) values (64, 64);
insert into Desarrolladorjuegos (id, id_des) values (65, 65);
insert into Desarrolladorjuegos (id, id_des) values (66, 66);
insert into Desarrolladorjuegos (id, id_des) values (67, 67);
insert into Desarrolladorjuegos (id, id_des) values (68, 68);
insert into Desarrolladorjuegos (id, id_des) values (69, 69);
insert into Desarrolladorjuegos (id, id_des) values (70, 70);
insert into Desarrolladorjuegos (id, id_des) values (71, 71);
insert into Desarrolladorjuegos (id, id_des) values (72, 72);
insert into Desarrolladorjuegos (id, id_des) values (73, 73);
insert into Desarrolladorjuegos (id, id_des) values (74, 74);
insert into Desarrolladorjuegos (id, id_des) values (75, 75);
insert into Desarrolladorjuegos (id, id_des) values (76, 76);
insert into Desarrolladorjuegos (id, id_des) values (77, 77);
insert into Desarrolladorjuegos (id, id_des) values (78, 78);
insert into Desarrolladorjuegos (id, id_des) values (79, 79);
insert into Desarrolladorjuegos (id, id_des) values (80, 80);
insert into Desarrolladorjuegos (id, id_des) values (81, 81);
insert into Desarrolladorjuegos (id, id_des) values (82, 82);
insert into Desarrolladorjuegos (id, id_des) values (83, 83);
insert into Desarrolladorjuegos (id, id_des) values (84, 84);
insert into Desarrolladorjuegos (id, id_des) values (85, 85);
insert into Desarrolladorjuegos (id, id_des) values (86, 86);
insert into Desarrolladorjuegos (id, id_des) values (87, 87);
insert into Desarrolladorjuegos (id, id_des) values (88, 88);
insert into Desarrolladorjuegos (id, id_des) values (89, 89);
insert into Desarrolladorjuegos (id, id_des) values (90, 90);
insert into Desarrolladorjuegos (id, id_des) values (91, 91);
insert into Desarrolladorjuegos (id, id_des) values (92, 92);
insert into Desarrolladorjuegos (id, id_des) values (93, 93);
insert into Desarrolladorjuegos (id, id_des) values (94, 94);

insert into Categoria_juegos (id_juego, categoria) values (1, 'Horror');
insert into Categoria_juegos (id_juego, categoria) values (2, 'Horror');
insert into Categoria_juegos (id_juego, categoria) values (3, 'Horror');
insert into Categoria_juegos (id_juego, categoria) values (4, 'Horror');
insert into Categoria_juegos (id_juego, categoria) values (5, 'Horror');
insert into Categoria_juegos (id_juego, categoria) values (6, 'Horror');
insert into Categoria_juegos (id_juego, categoria) values (7, 'Horror');
insert into Categoria_juegos (id_juego, categoria) values (8, 'Horror');
insert into Categoria_juegos (id_juego, categoria) values (9, 'Horror');
insert into Categoria_juegos (id_juego, categoria) values (10, 'Horror');
insert into Categoria_juegos (id_juego, categoria) values (11, 'Horror');
insert into Categoria_juegos (id_juego, categoria) values (12, 'Horror');
insert into Categoria_juegos (id_juego, categoria) values (13, 'Horror');
insert into Categoria_juegos (id_juego, categoria) values (14, 'Horror');
insert into Categoria_juegos (id_juego, categoria) values (15, 'Horror');
insert into Categoria_juegos (id_juego, categoria) values (16, 'Horror');
insert into Categoria_juegos (id_juego, categoria) values (17, 'Horror');
insert into Categoria_juegos (id_juego, categoria) values (18, 'Horror');
insert into Categoria_juegos (id_juego, categoria) values (19, 'Horror');
insert into Categoria_juegos (id_juego, categoria) values (20, 'Horror');
insert into Categoria_juegos (id_juego, categoria) values (21, 'Horror');
insert into Categoria_juegos (id_juego, categoria) values (22, 'Horror');
insert into Categoria_juegos (id_juego, categoria) values (23, 'Horror');
insert into Categoria_juegos (id_juego, categoria) values (24, 'Horror');
insert into Categoria_juegos (id_juego, categoria) values (25, 'Horror');
insert into Categoria_juegos (id_juego, categoria) values (26, 'Horror');
insert into Categoria_juegos (id_juego, categoria) values (27, 'Horror');
insert into Categoria_juegos (id_juego, categoria) values (28, 'Horror');
insert into Categoria_juegos (id_juego, categoria) values (29, 'Horror');
insert into Categoria_juegos (id_juego, categoria) values (30, 'Horror');
insert into Categoria_juegos (id_juego, categoria) values (31, 'Action');
insert into Categoria_juegos (id_juego, categoria) values (32, 'Action');
insert into Categoria_juegos (id_juego, categoria) values (33, 'Action');
insert into Categoria_juegos (id_juego, categoria) values (34, 'Action');
insert into Categoria_juegos (id_juego, categoria) values (35, 'Action');
insert into Categoria_juegos (id_juego, categoria) values (36, 'Action');
insert into Categoria_juegos (id_juego, categoria) values (37, 'Action');
insert into Categoria_juegos (id_juego, categoria) values (38, 'Action');
insert into Categoria_juegos (id_juego, categoria) values (39, 'Action');
insert into Categoria_juegos (id_juego, categoria) values (40, 'Action');
insert into Categoria_juegos (id_juego, categoria) values (41, 'Action');
insert into Categoria_juegos (id_juego, categoria) values (42, 'Action');
insert into Categoria_juegos (id_juego, categoria) values (43, 'Action');
insert into Categoria_juegos (id_juego, categoria) values (44, 'Action');
insert into Categoria_juegos (id_juego, categoria) values (45, 'Action');
insert into Categoria_juegos (id_juego, categoria) values (46, 'Action');

insert into Categoria_juegos (id_juego, categoria) values (47, 'Action');
insert into Categoria_juegos (id_juego, categoria) values (48, 'Action');
insert into Categoria_juegos (id_juego, categoria) values (49, 'Action');
insert into Categoria_juegos (id_juego, categoria) values (50, 'Action');
insert into Categoria_juegos (id_juego, categoria) values (51, 'Action');
insert into Categoria_juegos (id_juego, categoria) values (52, 'Action');
insert into Categoria_juegos (id_juego, categoria) values (53, 'Action');
insert into Categoria_juegos (id_juego, categoria) values (54, 'Action');
insert into Categoria_juegos (id_juego, categoria) values (55, 'Action');
insert into Categoria_juegos (id_juego, categoria) values (56, 'Action');
insert into Categoria_juegos (id_juego, categoria) values (57, 'Action');
insert into Categoria_juegos (id_juego, categoria) values (58, 'Action');
insert into Categoria_juegos (id_juego, categoria) values (59, 'Action');
insert into Categoria_juegos (id_juego, categoria) values (60, 'Action');
insert into Categoria_juegos (id_juego, categoria) values (61, 'Strategy');
insert into Categoria_juegos (id_juego, categoria) values (62, 'Strategy');
insert into Categoria_juegos (id_juego, categoria) values (63, 'Strategy');
insert into Categoria_juegos (id_juego, categoria) values (64, 'Strategy');
insert into Categoria_juegos (id_juego, categoria) values (65, 'Strategy');
insert into Categoria_juegos (id_juego, categoria) values (66, 'Strategy');
insert into Categoria_juegos (id_juego, categoria) values (67, 'Strategy');
insert into Categoria_juegos (id_juego, categoria) values (68, 'Strategy');
insert into Categoria_juegos (id_juego, categoria) values (69, 'Strategy');
insert into Categoria_juegos (id_juego, categoria) values (70, 'Strategy');
insert into Categoria_juegos (id_juego, categoria) values (71, 'Strategy');
insert into Categoria_juegos (id_juego, categoria) values (72, 'Strategy');
insert into Categoria_juegos (id_juego, categoria) values (73, 'Strategy');
insert into Categoria_juegos (id_juego, categoria) values (74, 'Strategy');
insert into Categoria_juegos (id_juego, categoria) values (75, 'Strategy');
insert into Categoria_juegos (id_juego, categoria) values (76, 'Strategy');
insert into Categoria_juegos (id_juego, categoria) values (77, 'Strategy');
insert into Categoria_juegos (id_juego, categoria) values (78, 'Strategy');
insert into Categoria_juegos (id_juego, categoria) values (79, 'Strategy');
insert into Categoria_juegos (id_juego, categoria) values (80, 'Strategy');
insert into Categoria_juegos (id_juego, categoria) values (81, 'Fighting');
insert into Categoria_juegos (id_juego, categoria) values (82, 'Fighting');
insert into Categoria_juegos (id_juego, categoria) values (83, 'Fighting');
insert into Categoria_juegos (id_juego, categoria) values (84, 'Fighting');
insert into Categoria_juegos (id_juego, categoria) values (85, 'Fighting');
insert into Categoria_juegos (id_juego, categoria) values (86, 'Fighting');
insert into Categoria_juegos (id_juego, categoria) values (87, 'Fighting');
insert into Categoria_juegos (id_juego, categoria) values (88, 'Fighting');
insert into Categoria_juegos (id_juego, categoria) values (89, 'Fighting');
insert into Categoria_juegos (id_juego, categoria) values (90, 'Fighting');
insert into Categoria_juegos (id_juego, categoria) values (91, 'Survival');
insert into Categoria_juegos (id_juego, categoria) values (92, 'Survival');
insert into Categoria_juegos (id_juego, categoria) values (93, 'Survival');
insert into Categoria_juegos (id_juego, categoria) values (94, 'Survival');


insert into Jugando (id_usuario, id_juego) values (68, 68);
insert into Jugando (id_usuario, id_juego) values (58, 4);
insert into Jugando (id_usuario, id_juego) values (8, 37);
insert into Jugando (id_usuario, id_juego) values (81, 89);
insert into Jugando (id_usuario, id_juego) values (85, 7);
insert into Jugando (id_usuario, id_juego) values (93, 3);
insert into Jugando (id_usuario, id_juego) values (85, 72);
insert into Jugando (id_usuario, id_juego) values (24, 30);
insert into Jugando (id_usuario, id_juego) values (67, 72);
insert into Jugando (id_usuario, id_juego) values (84, 88);
insert into Jugando (id_usuario, id_juego) values (94, 62);
insert into Jugando (id_usuario, id_juego) values (94, 50);
insert into Jugando (id_usuario, id_juego) values (90, 27);
insert into Jugando (id_usuario, id_juego) values (92, 63);
insert into Jugando (id_usuario, id_juego) values (33, 88);
insert into Jugando (id_usuario, id_juego) values (83, 39);
insert into Jugando (id_usuario, id_juego) values (8, 89);
insert into Jugando (id_usuario, id_juego) values (62, 57);
insert into Jugando (id_usuario, id_juego) values (100, 68);
insert into Jugando (id_usuario, id_juego) values (21, 7);
insert into Jugando (id_usuario, id_juego) values (91, 63);
insert into Jugando (id_usuario, id_juego) values (42, 24);
insert into Jugando (id_usuario, id_juego) values (90, 17);
insert into Jugando (id_usuario, id_juego) values (36, 37);
insert into Jugando (id_usuario, id_juego) values (64, 38);
insert into Jugando (id_usuario, id_juego) values (51, 59);
insert into Jugando (id_usuario, id_juego) values (31, 50);
insert into Jugando (id_usuario, id_juego) values (21, 93);
insert into Jugando (id_usuario, id_juego) values (69, 39);
insert into Jugando (id_usuario, id_juego) values (92, 41);
insert into Jugando (id_usuario, id_juego) values (41, 4);
insert into Jugando (id_usuario, id_juego) values (8, 7);
insert into Jugando (id_usuario, id_juego) values (4, 25);
insert into Jugando (id_usuario, id_juego) values (30, 47);
insert into Jugando (id_usuario, id_juego) values (94, 34);
insert into Jugando (id_usuario, id_juego) values (10, 40);
insert into Jugando (id_usuario, id_juego) values (79, 75);
insert into Jugando (id_usuario, id_juego) values (24, 69);
insert into Jugando (id_usuario, id_juego) values (84, 74);
insert into Jugando (id_usuario, id_juego) values (14, 84);
insert into Jugando (id_usuario, id_juego) values (25, 44);
insert into Jugando (id_usuario, id_juego) values (63, 23);
insert into Jugando (id_usuario, id_juego) values (73, 89);
insert into Jugando (id_usuario, id_juego) values (99, 62);
insert into Jugando (id_usuario, id_juego) values (40, 45);
insert into Jugando (id_usuario, id_juego) values (53, 14);
insert into Jugando (id_usuario, id_juego) values (23, 38);
insert into Jugando (id_usuario, id_juego) values (43, 59);
insert into Jugando (id_usuario, id_juego) values (95, 82);
insert into Jugando (id_usuario, id_juego) values (48, 75);
insert into Jugando (id_usuario, id_juego) values (78, 67);
insert into Jugando (id_usuario, id_juego) values (86, 46);
insert into Jugando (id_usuario, id_juego) values (14, 86);
insert into Jugando (id_usuario, id_juego) values (11, 27);
insert into Jugando (id_usuario, id_juego) values (43, 66);
insert into Jugando (id_usuario, id_juego) values (8, 54);
insert into Jugando (id_usuario, id_juego) values (45, 59);
insert into Jugando (id_usuario, id_juego) values (42, 58);
insert into Jugando (id_usuario, id_juego) values (38, 29);
insert into Jugando (id_usuario, id_juego) values (46, 57);
insert into Jugando (id_usuario, id_juego) values (3, 47);
insert into Jugando (id_usuario, id_juego) values (23, 8);
insert into Jugando (id_usuario, id_juego) values (64, 55);
insert into Jugando (id_usuario, id_juego) values (81, 43);
insert into Jugando (id_usuario, id_juego) values (97, 33);
insert into Jugando (id_usuario, id_juego) values (96, 41);
insert into Jugando (id_usuario, id_juego) values (66, 10);
insert into Jugando (id_usuario, id_juego) values (89, 34);
insert into Jugando (id_usuario, id_juego) values (18, 23);
insert into Jugando (id_usuario, id_juego) values (13, 29);
insert into Jugando (id_usuario, id_juego) values (91, 60);
insert into Jugando (id_usuario, id_juego) values (28, 52);
insert into Jugando (id_usuario, id_juego) values (48, 63);
insert into Jugando (id_usuario, id_juego) values (37, 92);
insert into Jugando (id_usuario, id_juego) values (64, 92);
insert into Jugando (id_usuario, id_juego) values (24, 15);
insert into Jugando (id_usuario, id_juego) values (2, 32);
insert into Jugando (id_usuario, id_juego) values (99, 39);
insert into Jugando (id_usuario, id_juego) values (64, 81);
insert into Jugando (id_usuario, id_juego) values (45, 49);
insert into Jugando (id_usuario, id_juego) values (80, 26);
insert into Jugando (id_usuario, id_juego) values (61, 29);
insert into Jugando (id_usuario, id_juego) values (36, 38);
insert into Jugando (id_usuario, id_juego) values (91, 2);
insert into Jugando (id_usuario, id_juego) values (51, 12);
insert into Jugando (id_usuario, id_juego) values (53, 4);
insert into Jugando (id_usuario, id_juego) values (9, 78);
insert into Jugando (id_usuario, id_juego) values (35, 13);
insert into Jugando (id_usuario, id_juego) values (47, 8);
insert into Jugando (id_usuario, id_juego) values (93, 43);
insert into Jugando (id_usuario, id_juego) values (30, 65);
insert into Jugando (id_usuario, id_juego) values (5, 50);
insert into Jugando (id_usuario, id_juego) values (68, 49);
insert into Jugando (id_usuario, id_juego) values (6, 18);
insert into Jugando (id_usuario, id_juego) values (91, 64);
insert into Jugando (id_usuario, id_juego) values (92, 48);